### ISSUE TITLE
Bug or 我使用不当

### ISSUE THREAD

**Issue by sjsdfg** [linbaiye/yobatis#54]
我写了一个测试用例代码
```
@Test
    public void testQuery() {
        NormalGlassCriteria criteria = new NormalGlassCriteria()
                .ascOrderBy("sale_date");
        List<NormalGlass> glasses = normalGlassDao.selectList(criteria);
        System.out.println(glasses.size());
    }
```

然后抛除异常
```
Cause: java.lang.RuntimeException: Empty criteria is not allowed.

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy53.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at cn.sjsdfg.glass.dao.impl.NormalGlassDaoImpl.selectList(NormalGlassDaoImpl.java:34)
	at cn.sjsdfg.glass.dao.NormalGlassDaoTest.testQuery(NormalGlassDaoTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

我很好奇，我自己  new  的对象，也增加了属性，为什么是 `Empty criteria` ?

**Comment by sjsdfg** [comment]
我知道了 `asOrderBy` 不算属性
那我想查全部信息，只能使用 **主键非空** 作为查询条件？

**Comment by linbaiye** [comment]
> 我知道了 `asOrderBy` 不算属性
> 那我想查全部信息，只能使用 **主键非空** 作为查询条件？

是的，这个是故意这样做的，以防意外影响到全表，请使用*主键非空*。

**Comment by linbaiye** [comment]
List<NormalGlass> glasses = normalGlassDao.selectList(NormalGlassCriteria.idIsNotNull().ascOrderBy("sale_date"));

**Comment by sjsdfg** [comment]
> > 我知道了 `asOrderBy` 不算属性
> > 那我想查全部信息，只能使用 **主键非空** 作为查询条件？
> 
> 是的，这个是故意这样做的，以防意外影响到全表，请使用_主键非空_。可以写成这样:
> List glasses = normalGlassDao.selectList(NormalGlassCriteria.idIsNotNull().ascOrderBy("sale_date"));

okok
